{% set name = "emfile" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/emfile-{{ version }}.tar.gz
  sha256: d7e9114aac5e2a29db9d77ab669659499c2f8c38ca13a5ff468c39ec89181a9b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - numpy
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - emfile
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/brisvag/emfile
  summary: Basic utility to read tomography data from files in `*.em` format.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - brisvag
    - goanpeca
